### ISSUE TITLE
Argument of type '"DELETE"' is not assignable to parameter of type '"PATCH" | "POST" | "PUT"

### ISSUE THREAD

**Issue by hmmhmmhm** [samchon/nestia-fetcher#8]
> src/api/functional/auth/user/account/index.ts:27:5 - error TS2345: Argument of type '"DELETE"' is not assignable to parameter of type '"PATCH" | "POST" | "PUT"'.
![스크린샷 2022-07-12 오후 1 06 17](https://user-images.githubusercontent.com/38493722/178406399-3402616a-302a-431c-b52c-245448973284.png)
![스크린샷 2022-07-12 오후 1 06 33](https://user-images.githubusercontent.com/38493722/178406421-746f8af7-1dba-4c2d-b768-91f14b91baae.png)

**Comment by samchon** [comment]
The type payload seems like `request body`.

`DELETE` method cannot have the `request body`.

**Comment by hmmhmmhm** [comment]
aaaaha i got it thx...!

**Comment by samchon** [comment]
It would better to thrown an error in the `nestia` builder level.
